#!/bin/bash

url=https://tutti-ch.atlassian.net
ticket_id=$(echo $1 | tr '[:lower:]' '[:upper:]')

name=$(curl $url/rest/api/2/issue/$1\?fields\=summary \
--user $GIT_JIRA_EMAIL:$GIT_JIRA_TOKEN 2>&1 | \
grep -o '"summary": *"[^"]*"' | \
grep -o '"[^"]*"$' | \
sed "s/\"//g" | \
tr '[:upper:]' '[:lower:]' | \
tr ' ' '-' | \
tr '.' '-' | \
tr -d ':' | \
tr -d '[' | \
tr -d ']')

full_name="$ticket_id-$name"

if [ -z "$name" ]; then
    echo "Something went wrong. Couldn't find a ticket with ID $1"
    exit 1
else
    echo "Creating branch: $full_name"
    git fetch
    git checkout $full_name 2>/dev/null || git checkout -b $full_name origin/master
fi
